- name: Install and Configure ISC DHCP on Ubuntu Hosts
  hosts: dhcp.dylanlab.xyz
  become: yes
  ignore_errors: yes
  tasks:

  - name: Apt Update
    apt:
      update_cache: yes

  - name: Install isc-dhcp-server from Apt
    apt:
      name:
        - isc-dhcp-server
      state: present

  - name: Set named.conf.options Config File
    copy:
      dest: "/etc/dhcp/dhcpd.conf"
      content: |
        ddns-updates on;
        ddns-update-style interim;
        update-static-leases on;
        authoritative;
        key rndc-key { algorithm hmac-sha256; secret "MebAHyF48jzn3I1Z/ipGm/N8mXLonXUWhl3HwaG2cRs=";}
        allow unknown-clients;
        use-host-decl-names on;
        default-lease-time 1814400; #21 days
        max-lease-time 1814400; #21 days
        log-facility local7;

        zone dylanlab.xyz. {
          primary 10.0.20.5; # This server is the primary DNS server for the zone
          key rndc-key; # Use the key we defined earlier for dynamic updates
        }
        
        zone 20.0.10.in-addr.arpa. {
          primary 10.0.20.5; # This server is the primary DNS server for the zone
          key rndc-key; # Use the key we defined earlier for dynamic updates
        }

        subnet 10.0.20.0 netmask 255.255.255.0 {
          range 10.0.20.50 10.0.20.250;
          option subnet-mask 255.255.255.0;
          option routers 10.0.20.1;
          option domain-name-servers 10.0.20.5, 10.0.20.6;
          option domain-name "dylanlab.xyz";
          ddns-domainname "dylanlab.xyz.";
          ddns-rev-domainname "in-addr.arpa.";
        }

  
  - name: Reload dhcp server
    systemd:
      name: isc-dhcp-server
      state: restarted