all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/ansible_id_rsa
    ansible_python_interpreter: /usr/bin/python3

  children:
    utilities:
      hosts:
        us20-netbox.dylanlab.xyz:
        us20-openvpn.dylanlab.xyz:
        us20-rancher.dylanlab.xyz:

    dns:
      hosts:
        ns1.dylanlab.xyz:
          ansible_host: 10.0.20.5
        ns2.dylanlab.xyz:
          ansible_host: 10.0.20.6
          
    k8s:
      children: 
        k8s_controllers:
          hosts:
            us20-k8c-[01:03].dylanlab.xyz:

        k8s_workers:
          hosts:
            us20-k8w-[01:04].dylanlab.xyz:
