all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/ansible_id_rsa
    ansible_python_interpreter: /usr/bin/python3
    #host_key_checking: False
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" 

  children:
    utilities:
      hosts:
        us20-netbox.dylanlab.xyz:
        us20-openvpn.dylanlab.xyz:
        us20-rancher.dylanlab.xyz:
        dhcp.dylanlab.xyz:
          ansible_host: 10.0.20.4

    dns:
      hosts:
        ns1.dylanlab.xyz:
          ansible_host: 10.0.20.5
        ns2.dylanlab.xyz:
          ansible_host: 10.0.20.6

    networking:
      hosts:
        edgerouter.dylanlab.xyz:
          ansible_host: 10.0.20.1
          ansible_network_os: edgeos
          ansible_python_interpreter: /usr/bin/python2.7