- name: Configure EdgeRouter
  hosts: edgerouter.dylanlab.xyz
  connection: network_cli
  
  #gather_facts: no
  tasks:

    #- name: Configure the remote device
    #  community.network.edgeos_config:
    #    lines:
    #      - set system host-name edgeos_test
    
    - edgeos_command:
        commands:
          - show date
          - show interfaces
          - show hardware cpu
          - show hardware mem
      register: output

    - debug:
        var: output.stdout_lines