# Do not include NS records
# When value is FQDN, include . on end
#
# BASE DOMAIN: dylanlab.xyz
---
records:
  - host: xoa
    type: A
    value: 10.0.20.123
    record_state: present

  - host: netbox
    type: A
    value: 10.0.20.17
    record_state: present

  - host: ovpn
    type: A
    value: 10.0.20.15
    record_state: present