# Do not include NS records
# When value is FQDN, include . on end
#
# BASE DOMAIN: 20.0.10.in-addr.arpa
---
records:
  - host: 33
    type: PTR
    value: test333.dylanlab.xyz.
    record_state: present
  
  - host: 35
    type: PTR
    value: test335.dylanlab.xyz.
    record_state: present
