# Do not include NS records
# When value is FQDN, include . on end
#
# BASE DOMAIN: dylanlab.xyz
---
records:
  - host: xoa
    type: A
    value: 10.0.20.123
    record_state: present

  - host: test333
    type: A
    value: 10.0.20.33
    record_state: absent
  
  - host: test335
    type: A
    value: 10.0.20.35
    record_state: absent

  - host: test336
    type: A
    value: 10.0.20.36
    record_state: absent

  - host: test337
    type: A
    value: 10.0.20.37
    record_state: absent