# Do not include NS records
# When value is FQDN, include . on end
#
# BASE DOMAIN: example.com
---
records:
  - host: subdomain1
    type: A
    value: 10.0.20.33
    record_state: present
  
  - host: subdomain2
    type: A
    value: 10.0.20.35
    record_state: present

  - host: subdomain3
    type: A
    value: 10.0.20.36
    record_state: absent #To remove a zone, change record_state to absent, if you simply delete it, the records wont delete

  - host: subdomain4
    type: A
    value: 10.0.20.37
    record_state: absent