# https://arstechnica.com/gadgets/2020/08/understanding-dns-anatomy-of-a-bind-zone-file/
---
zone_config:
  domain: dylanlab.xyz

  # First in list will be considered master
  # Do not include zone_domain in hostname: "ns1", "ns2"
  # ipv4_r is the RDNS IP
  nameservers:
    - hostname: ns1
      ipv4: 10.0.20.5
      rdns_ipv4: 5.20.0.10.in-addr.arpa
    - hostname: ns2
      ipv4: 10.0.20.6
      rdns_ipv4: 6.20.0.10.in-addr.arpa

  ttl: 604801
  soa_serial: 100
  soa_refresh: 604800
  soa_retry: 86400
  soa_expire: 2419200
  soa_minimum: 604800

  # Only include first part of email, should be fine to leave as is
  admin_email: admin
