---
subnets:
#Shopnet
  - subnet: 10.0.20.0
    netmask: 255.255.255.0
    range:
      start: 10.0.20.50
      end: 10.0.20.250
    options:
      routers: 
        - 10.0.20.1
      dns:
        - 10.0.20.5
        - 10.0.20.6
      search_domain: dylanlab.xyz
    ddns:
      domainname: dylanlab.xyz
      revdomainname: in-addr.arpa

#K8sNet
  - subnet: 10.1.0.0
    netmask: 255.255.0.0
    range:
      #Reserve the first /24 and the final /24
      start: 10.1.1.0
      end: 10.1.254.255
    options:
      routers: 
        - 10.1.0.1
      dns:
        - 10.0.20.5
        - 10.0.20.6
      search_domain: k8s.dylanlab.xyz
    ddns:
      domainname: k8s.dylanlab.xyz
      revdomainname: in-addr.arpa