- name: Install and Configure BIND9 on Ubuntu Hosts
  hosts: dns
  become: yes
  ignore_errors: yes
  tasks:

  - name: "loop through list"
    debug:
      msg: "Hostname: {{ item.hostname }}, IP: {{ item.ipv4 }}, type: {{ item.type }}"
    with_items:
      - { hostname: test.dylanlab.xyz, ipv4: 10.0.20.31, type: A}
      - { hostname: test2.dylanlab.xyz, ipv4: 10.0.20.32, type: A}
      - { hostname: test3.dylanlab.xyz, ipv4: 10.0.20.33, type: A}
  - name: Apt Update
    apt:
      update_cache: yes

  - name: Install Bind9 from Apt
    apt:
      name:
        - bind9 
        - bind9utils
        - bind9-doc
      state: present

  - name: Remove Existing Config Files
    file:
      state: absent
      path: "{{ item }}"
    with_items:
      - /etc/bind/named.conf.options
      - /etc/bind/named.conf.local
      #- /var/lib/bind/zones/db.*
  
  - name: Make Zone Directory
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: bind
      mode: '0775'
    with_items:
      - /var/lib/bind/zones

  - name: Create New Config Files
    file:
      state: touch
      path: "{{ item }}"
      owner: root
      group: bind
      mode: '0775'
    with_items:
      - /etc/bind/named.conf.options
      - /etc/bind/named.conf.local
      #- /var/lib/bind/zones/db.dylanlab.xyz
      #- /var/lib/bind/zones/db.10.0.20

  
  - name: Set named.conf.options Config File
    copy:
      dest: "/etc/bind/named.conf.options"
      content: |
        options {
          directory "/var/cache/bind";

          recursion yes;                 # enables resursive queries
          allow-recursion { any; };  # allows recursive queries from "trusted" clients
          listen-on { 0.0.0.0/0; };   # ns1 private IP address - listen on private network only
          allow-transfer { none; };      # disable zone transfers by default

          forwarders {
            8.8.8.8;
            8.8.4.4;
          };
        };

  - name: Set named.conf.local Config File - NS1
    copy:
      dest: "/etc/bind/named.conf.local"
      content: |
        key "rndc-key" {
            algorithm hmac-sha256;
            secret "MebAHyF48jzn3I1Z/ipGm/N8mXLonXUWhl3HwaG2cRs=";
        };
        zone "dylanlab.xyz" {
            type master;
            file "/var/lib/bind/zones/db.dylanlab.xyz"; 	# zone file path
            allow-transfer { 10.0.20.6; };           # ns2 private IP address - secondary
            allow-update { key "rndc-key"; };
        };

        zone "20.0.10.in-addr.arpa" {
            type master;
            file "/var/lib/bind/zones/db.10.0.20";  # 10.0.20.0/24 subnet
            allow-transfer { 10.0.20.6; };  # ns2 private IP address - secondary
            allow-update { key "rndc-key"; };
        };
    when: ansible_hostname == "ns1"

  - name: Set named.conf.local Config File - NS2
    copy:
      dest: "/etc/bind/named.conf.local"
      content: |
        zone "dylanlab.xyz" {
            type slave;
            file "/var/lib/bind/zones/db.dylanlab.xyz"; 	# zone file path
            masters { 10.0.20.5; };           # ns2 private IP address - secondary
        };

        zone "20.0.10.in-addr.arpa" {
            type slave;
            file "/var/lib/bind/zones/db.10.0.20";  # 10.0.20.0/24 subnet
            masters { 10.0.20.5; };  # ns2 private IP address - secondary
        };
    when: ansible_hostname == "ns2"

  - name: Set db.dylanlab.xyz Zone file
    blockinfile:
      path: "/var/lib/bind/zones/db.dylanlab.xyz"
      marker: "; {mark} Zone File"
      block: |
        $TTL    604800
        @       IN      SOA     ns1.dylanlab.xyz. admin.dylanlab.xyz. (
                    {{ ansible_date_time.epoch }}     ; Serial
                    604800     ; Refresh
                      86400     ; Retry
                    2419200     ; Expire
                    604800 )   ; Negative Cache TTL
        ;
        ; name servers - NS records
            IN      NS      ns1.dylanlab.xyz.
            IN      NS      ns2.dylanlab.xyz.

        ; name servers - A records
        ns1.dylanlab.xyz.          IN      A       10.0.20.5
        ns2.dylanlab.xyz.          IN      A       10.0.20.6
        test4.dylanlab.xyz.          IN      A       10.0.20.34
    when: ansible_hostname == "ns1"

  - name: Set rdns Zone File
    blockinfile:
      path: "/var/lib/bind/zones/db.10.0.20"
      marker: "; {mark} Zone File"
      block: |
        $TTL    604800
        @       IN      SOA     dylanlab.xyz. admin.dylanlab.xyz. (
                                {{ ansible_date_time.epoch }}         ; Serial
                                604800         ; Refresh
                                  86400         ; Retry
                                2419200         ; Expire
                                604800 )       ; Negative Cache TTL
        ; name servers
              IN      NS      ns1.dylanlab.xyz.
              IN      NS      ns2.dylanlab.xyz.

        ; PTR Records
        10.0.20.5   IN      PTR     ns1.dylanlab.xyz.    ; 10.0.20.5
        10.0.20.6   IN      PTR     ns2.dylanlab.xyz.    ; 10.0.20.6
        10.0.20.34   IN      PTR     test4.dylanlab.xyz.    ; 10.0.20.6
    when: ansible_hostname == "ns1"

  - name: Reload bind9
    systemd:
      name: bind9
      state: reloaded