- name: Install and Configure BIND9 on Ubuntu Hosts
  hosts: ns1.dylanlab.xyz, ns2.dylanlab.xyz
  become: yes
  ignore_errors: yes
  tasks:

  - name: Apt Update
    apt:
      update_cache: yes

  - name: Install Docker from Apt
    apt:
      name:
        - bind9 
        - bind9utils
        - bind9-doc
      state: present

  - name: Remove Existing Config Files
    file:
      state: absent
      path: "{{ item }}""
    with_items:
      - "/etc/bind/named.conf.options"
      - "/etc/bind/named.conf.local"

  - name: Create New Config Files
    file:
      state: touch
      path: "{{ item }}"
    with_items:
      - "/etc/bind/named.conf.options"
      - "/etc/bind/named.conf.local"

  - name: Make Zone Directory
    file:
      path: "/etc/bind/zones"
      state: directory

  - name: Set named.conf.options Config File
    blockinfile:
      path: "/etc/bind/named.conf.options"
      block: |
        options {
          directory "/var/cache/bind";

          recursion yes;                 # enables resursive queries
          allow-recursion { any; };  # allows recursive queries from "trusted" clients
          listen-on { 0.0.0.0/0; };   # ns1 private IP address - listen on private network only
          allow-transfer { none; };      # disable zone transfers by default

          forwarders {
            8.8.8.8;
            8.8.4.4;
          };
        };

  - name: Set named.conf.local Config File - NS1
    blockinfile:
      path: "/etc/bind/named.conf.local"
      block: |
        zone "dylanlab.xyz" {
            type master;
            file "/etc/bind/zones/db.dylanlab.xyz"; 	# zone file path
            allow-transfer { 10.0.20.6; };           # ns2 private IP address - secondary
        };

        zone "20.0.10.in-addr.arpa" {
            type master;
            file "/etc/bind/zones/db.10.0.20";  # 10.128.0.0/16 subnet
            allow-transfer { 10.0.20.6; };  # ns2 private IP address - secondary
        };
    when: {{ ansible_hostname }} == "ns1"

  - name: Set named.conf.local Config File - NS2
    blockinfile:
      path: "/etc/bind/named.conf.local"
      block: |
        zone "dylanlab.xyz" {
            type slave;
            file "/etc/bind/zones/db.dylanlab.xyz"; 	# zone file path
            masters { 10.0.20.5; };           # ns2 private IP address - secondary
        };

        zone "20.0.10.in-addr.arpa" {
            type slave;
            file "/etc/bind/zones/db.10.0.20";  # 10.128.0.0/16 subnet
            masters { 10.0.20.6; };  # ns2 private IP address - secondary
        };
    when: {{ ansible_hostname }} == "ns2"

  - name: Set named.conf.local Config File
    blockinfile:
      path: "/etc/bind/zones/db.dylanlab.xyz"
      block: |
        $TTL    604800
        @       IN      SOA     ns1.dylanlab.xyz. admin.dylanlab.xyz. (
                          3     ; Serial
                    604800     ; Refresh
                      86400     ; Retry
                    2419200     ; Expire
                    604800 )   ; Negative Cache TTL
        ;
        ; name servers - NS records
            IN      NS      ns1.dylanlab.xyz.
            IN      NS      ns2.dylanlab.xyz.

        ; name servers - A records
        ns1.dylanlab.xyz.          IN      A       10.128.10.5
        ns2.dylanlab.xyz.          IN      A       10.128.20.6
    when: {{ ansible_hostname }} == "ns1"

  - name: Set named.conf.local Config File
    blockinfile:
      path: "/etc/bind/zones/db.dylanlab.xyz"
      block: |
        $TTL    604800
        @       IN      SOA     dylanlab.xyz. admin.dylanlab.xyz. (
                                      3         ; Serial
                                604800         ; Refresh
                                  86400         ; Retry
                                2419200         ; Expire
                                604800 )       ; Negative Cache TTL
        ; name servers
              IN      NS      ns1.dylanlab.xyz.
              IN      NS      ns2.dylanlab.xyz.

        ; PTR Records
        5   IN      PTR     ns1.dylanlab.xyz.    ; 10.0.20.5
        6   IN      PTR     ns2.dylanlab.xyz.    ; 10.0.20.6
    when: {{ ansible_hostname }} == "ns1"

  - name: Reload bind9
    systemd:
      name: bind9
      state: reloaded