- name: Install and Configure BIND9 on Ubuntu
  hosts: dns
  become: yes
  ignore_errors: yes
  tasks:

    - name: Load Variables
      include_vars: "{{ item }}"
      with_items:
        - "vars/vars.yaml"
        - "vars/zones.yaml"
        - "vars/keys.yaml"

    - name: Apt Update
      apt:
        update_cache: yes
      changed_when: false

    - name: Install Bind9 from Apt
      apt:
        name:
          - bind9 
          - bind9utils
        state: present
    
    - name: Make Directories
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: bind
        mode: '0775'
      with_items:
        - /var/lib/bind/zones

    - name: Set named.conf.options
      template:
        src: templates/named.conf.options.j2
        dest: /etc/bind/named.conf.options
      notify: reload_bind

    - name: Set Master named.conf.local
      template:
        src: templates/named.conf.local.master.j2
        dest: /etc/bind/named.conf.local
      notify: reload_bind
      when: ansible_hostname == "ns1"

    - name: Set Master rndc.key
      template:
        src: templates/rndc.key.j2
        dest: /etc/bind/rndc.key
      register: rndc_key
      when: ansible_hostname == "ns1"

    - name: Restart BIND9 due to key change
      service:
        name: bind9
        state: restarted
      when: rndc_key.changed

    - name: Set Slave named.conf.local
      template:
        src: templates/named.conf.local.slave.j2
        dest: /etc/bind/named.conf.local
      notify: reload_bind
      when: ansible_hostname != "ns1"
    
    - name: RNDC Sync
      shell: "rndc sync"
      changed_when: false

    - name: RNDC Freeze Zones
      shell: "rndc freeze"
      changed_when: false

    - name: Configure Master Zone Files
      include_tasks: zone-update.yaml
      vars:
        zone: "{{ outer_item }}"
      with_items: 
        - "{{ zones }}"
      loop_control:
        loop_var: outer_item
      when: ansible_hostname == "ns1"

    - name: RNDC Thaw Zones
      shell: "rndc thaw"
      changed_when: false
    
    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      meta: flush_handlers

    - name: Collecting Service Facts
      service_facts:
      register: services_state

    - name: Named.service Status
      debug:
        var: services_state.ansible_facts.services['named.service'].state
    

  handlers:
    - name: reload_bind
      service: 
        name: bind9 
        state: restarted
        
